"""
Fetch all of andreiastra's iNaturalist observations at Kilcrohane Pier and write
a Markdown report with a thumbnail for each one to OUTPUT/kilcrohane.md.

An observation belongs to the site when its place_guess resolves to SITE via the
keyword list in site_names.py, or when its GPS position is within
CLUSTER_RADIUS_M of the centroid of those matches (catches observations logged
under a generic place name such as "Cork, Co. Cork, Ireland").

Usage:
  .venv/bin/python scripts/kilcrohane_observations.py
"""
import collections
import os
from datetime import date

from config import CLUSTER_RADIUS_M, OUTPUT_DIR, USER_ID
from generate_location_ratings import fetch_all_observations, haversine, photo_md
from site_names import SITE_KEYWORDS
from species_classification import species_type

SITE        = "Kilcrohane Pier"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "kilcrohane.md")


def named_at_site(obs):
    guess = (obs.get("place_guess") or "").lower()
    return any(name == SITE and keyword in guess for keyword, name in SITE_KEYWORDS)


def coords(obs):
    c = (obs.get("geojson") or {}).get("coordinates")
    return (c[1], c[0]) if c else None


def at_site(observations):
    """Observations named for the site, plus any within CLUSTER_RADIUS_M of it."""
    named = [o for o in observations if named_at_site(o)]
    points = [p for p in map(coords, named) if p]
    if not points:
        return named
    lat = sum(p[0] for p in points) / len(points)
    lon = sum(p[1] for p in points) / len(points)
    return [
        o for o in observations
        if o in named or (coords(o) and haversine(lat, lon, *coords(o)) <= CLUSTER_RADIUS_M)
    ]


def obs_url(obs):
    return obs.get("uri") or f"https://www.inaturalist.org/observations/{obs['id']}"


def names(obs):
    taxon = obs.get("taxon") or {}
    sci   = taxon.get("name") or ""
    return taxon.get("preferred_common_name") or sci or "Unidentified", sci


def render(obs_list, notes):
    research = sum(1 for o in obs_list if o.get("quality_grade") == "research")
    dives    = {o.get("observed_on") for o in obs_list if o.get("observed_on")}
    species  = collections.Counter((names(o)[0], names(o)[1], species_type(o)) for o in obs_list)

    lines = [
        f"# Observations at {SITE}\n",
        f"> Generated by `scripts/kilcrohane_observations.py` on {date.today()} "
        f"from live iNaturalist data for `{USER_ID}`.\n",
    ]
    lines += [f"> ⚠️ {n}" for n in notes]
    lines += [
        f"\n**{len(obs_list)}** observations · **{len(species)}** taxa · "
        f"**{len(dives)}** dates · **{research}** Research Grade, "
        f"**{len(obs_list) - research}** need ID\n",
        "## Species\n",
        "| Species | Organism Type | Observations |",
        "|---|---|---:|",
    ]
    for (common, sci, org_type), count in sorted(species.items(), key=lambda kv: (-kv[1], kv[0][0].lower())):
        label = f"**{common}**" + (f" (*{sci}*)" if sci and sci != common else "")
        lines.append(f"| {label} | {org_type} | {count} |")

    lines += [
        "\n## Observations\n",
        "| Photo | Date | Species | Organism Type |",
        "|---|---|---|---|",
    ]
    for obs in sorted(obs_list, key=lambda o: o.get("observed_on") or "", reverse=True):
        common, sci = names(obs)
        org_type = species_type(obs)
        label = f"[{common}]({obs_url(obs)})" + (f" (*{sci}*)" if sci and sci != common else "")
        lines.append(f"| {photo_md(obs)} | {obs.get('observed_on') or '—'} | {label} | {org_type} |")

    return "\n".join(lines) + "\n"


def main():
    notes = []
    observations = fetch_all_observations(notes)
    matches = at_site(observations)
    if not matches:
        print(f"No observations found at {SITE}.")
        return
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(render(matches, notes))
    print(f"Saved {len(matches)} of {len(observations)} observations → {os.path.normpath(OUTPUT_FILE)}")


if __name__ == "__main__":
    main()
