"""
Fetch andreiastra's nudibranch observations in Ireland from iNaturalist and
write a Markdown report, grouped by site, to OUTPUT/nudibranch_ireland.md.

Sites are resolved with the keyword list in site_names.py; places with no match
fall back to the first part of the observation's place_guess.

Usage:
  .venv/bin/python scripts/nudibranch_ireland.py
"""
import os
import time
from datetime import date

import requests

from config import (
    IRELAND_PLACE_ID as PLACE_ID,
    NUDIBRANCHIA_TAXON_ID as TAXON_ID,
    OBSERVATIONS_URL as BASE_URL,
    OUTPUT_DIR,
    PER_PAGE,
    THROTTLE_S,
    USER_ID,
)
from generate_location_ratings import photo_md
from site_names import SITE_KEYWORDS

OUTPUT_FILE = os.path.join(OUTPUT_DIR, "nudibranch_ireland.md")


def fetch_nudibranchs():
    print(f"Fetching nudibranch observations in Ireland for {USER_ID}…")
    all_obs, page = [], 1
    while True:
        r = requests.get(BASE_URL, params={
            "user_id":  USER_ID,
            "taxon_id": TAXON_ID,
            "place_id": PLACE_ID,
            "per_page": PER_PAGE,
            "page":     page,
        }, timeout=30)
        r.raise_for_status()
        data    = r.json()
        results = data.get("results", [])
        all_obs.extend(results)
        print(f"  page {page}: {len(results)} obs  (running total: {len(all_obs)})")
        if not results or len(all_obs) >= data.get("total_results", 0):
            break
        page += 1
        time.sleep(THROTTLE_S)
    return all_obs


def site_of(obs):
    """Canonical site name from site_names.py, else the first part of place_guess."""
    guess = obs.get("place_guess") or "Unknown location"
    lowered = guess.lower()
    for keyword, name in SITE_KEYWORDS:
        if keyword in lowered:
            return name
    return guess.split(",")[0].strip()


def obs_url(obs):
    return obs.get("uri") or f"https://www.inaturalist.org/observations/{obs['id']}"


def render(obs_list):
    by_site = {}
    for obs in obs_list:
        by_site.setdefault(site_of(obs), []).append(obs)

    research = sum(1 for o in obs_list if o.get("quality_grade") == "research")
    species  = {(o.get("taxon") or {}).get("id") for o in obs_list}

    lines = [
        "# Nudibranch observations in Ireland\n",
        f"> Generated by `scripts/nudibranch_ireland.py` on {date.today()} "
        f"from live iNaturalist data for `{USER_ID}`.\n",
        f"**{len(obs_list)}** observations · **{len(species)}** taxa · "
        f"**{len(by_site)}** sites · **{research}** Research Grade, "
        f"**{len(obs_list) - research}** need ID\n",
        "## Sites\n",
        "| Site | Observations | Taxa |",
        "|---|---:|---:|",
    ]
    ranked = sorted(by_site.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    for site, items in ranked:
        taxa = {(o.get("taxon") or {}).get("id") for o in items}
        lines.append(f"| {site} | {len(items)} | {len(taxa)} |")

    lines += [
        "\n## Observations\n",
        "| Site | Photo | Date | Species | Grade |",
        "|---|---|---|---|---|",
    ]
    for site, items in ranked:
        items.sort(key=lambda o: o.get("observed_on") or "")
        for i, obs in enumerate(items):
            taxon  = obs.get("taxon") or {}
            common = taxon.get("preferred_common_name") or taxon.get("name") or "Unknown"
            sci    = taxon.get("name") or ""
            label  = f"[{common}]({obs_url(obs)})"
            if sci and sci != common:
                label += f" (*{sci}*)"
            grade = "Research" if obs.get("quality_grade") == "research" else "Needs ID"
            cell  = f"**{site}**" if i == 0 else ""
            lines.append(
                f"| {cell} | {photo_md(obs)} | {obs.get('observed_on') or '—'} | {label} | {grade} |"
            )

    return "\n".join(lines) + "\n"


def main():
    obs_list = fetch_nudibranchs()
    if not obs_list:
        print("No nudibranch observations found in Ireland.")
        return
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(render(obs_list))
    print(f"Saved {len(obs_list)} observations → {os.path.normpath(OUTPUT_FILE)}")


if __name__ == "__main__":
    main()
